const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { normalizeScore } = require('../src/services/basketball-score.service');

test('basketball is an always-available single-server game with a persistent top-three leaderboard', () => {
  const model = fs.readFileSync(path.join(__dirname, '../src/models/GameSession.js'), 'utf8');
  const gameService = fs.readFileSync(path.join(__dirname, '../src/services/game.service.js'), 'utf8');
  const scoreService = fs.readFileSync(path.join(__dirname, '../src/services/basketball-score.service.js'), 'utf8');
  const app = fs.readFileSync(path.join(__dirname, '../src/app.js'), 'utf8');
  const admin = fs.readFileSync(path.join(__dirname, '../../frontend/js/admin-app.js'), 'utf8');
  const participant = fs.readFileSync(path.join(__dirname, '../../frontend/js/app.js'), 'utf8');
  const game = fs.readFileSync(path.join(__dirname, '../../frontend/basketball/basketball.js'), 'utf8');
  const routes = fs.readFileSync(path.join(__dirname, '../src/routes/basketball.routes.js'), 'utf8');
  const adminRoutes = fs.readFileSync(path.join(__dirname, '../src/routes/admin.routes.js'), 'utf8');
  const adminController = fs.readFileSync(path.join(__dirname, '../src/controllers/admin.controller.js'), 'utf8');
  const adminHtml = fs.readFileSync(path.join(__dirname, '../../frontend/admin.html'), 'utf8');
  const backendPackage = JSON.parse(fs.readFileSync(path.join(__dirname, '../package.json'), 'utf8'));

  assert.match(model, /'BASKETBALL'/);
  assert.match(gameService, /'BASKETBALL'/);
  assert.match(scoreService, /limit: 3/);
  assert.match(scoreService, /bestScore.*DESC/);
  assert.match(scoreService, /freePlay: true/);
  assert.match(scoreService, /participantId: Number\(participantId\), tableSessionId: Number\(tableSessionId\)/);
  assert.match(scoreService, /getPersonalBest\(participantId, tableSessionId\)/);
  assert.doesNotMatch(scoreService, /requireActiveBasketballGame/);
  assert.match(app, /app\.use\('\/api\/basketball'/);
  assert.match(app, /express\.static/);
  assert.match(admin, /renderBasketballLeaderboard/);
  assert.match(admin, /isFreePlayBasketball/);
  assert.match(participant, /appendBasketballLeaderboard/);
  assert.match(participant, /언제든 자유롭게 플레이/);
  assert.match(game, /basketball:leaderboard/);
  assert.match(game, /basketball:reset/);
  assert.match(game, /game:global:announced/);
  assert.match(game, /game:global:started/);
  assert.match(game, /global-game-notice/);
  assert.match(game, /window\.location\.replace/);
  assert.match(game, /\/api\/basketball\/scores/);
  assert.match(game, /JSON\.stringify\(\{ score: target \}\)/);
  assert.match(game, /const finalScore = score;[\s\S]*queueScoreSubmission\(finalScore\);[\s\S]*updateScore\(0\)/);
  assert.doesNotMatch(game, /localStorage\.setItem\('festival-basketball-best'[\s\S]{0,120}queueScoreSubmission\(score\)/);
  assert.doesNotMatch(routes, /gameId/);
  assert.match(adminRoutes, /basketball\/reset/);
  assert.match(adminController, /BasketballScore\.destroy\(\{ where: \{\} \}\)/);
  assert.match(adminController, /emit\('basketball:reset'\)/);
  assert.match(adminHtml, /id="basketball-ranking-reset-btn"/);
  assert.match(admin, /resetBasketballLeaderboard/);
  assert.match(participant, /basketball:reset/);
  assert.match(backendPackage.scripts.start, /npm run migrate/);
});

test('basketball scores only accept realistic positive integer streaks', () => {
  assert.equal(normalizeScore('12'), 12);
  assert.throws(() => normalizeScore(0), (error) => error.code === 'INVALID_BASKETBALL_SCORE');
  assert.throws(() => normalizeScore(1.5), (error) => error.code === 'INVALID_BASKETBALL_SCORE');
  assert.throws(() => normalizeScore(10001), (error) => error.code === 'INVALID_BASKETBALL_SCORE');
});
